version: '3.7'
services:
  database:
    image: mysql:latest
    container_name: db_nestjs
    environment:
      - MYSQL_DATABASE=nestjs
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
